import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Edit3, KeyRound, Plus, Search, ShieldCheck, UserCheck, UserX, X } from 'lucide-react'
import { Header } from '@/components/Header'
import { Alert } from '@/components/Alert'
import { Button } from '@/components/Button'
import { useAuth } from '@/contexts/AuthContext'
import { activarUsuario, crearUsuario, desactivarUsuario, editarUsuario, listarUsuarios, obtenerMetadatosUsuarios, resetearContrasena, InstitucionAdmin, RolAdmin, UsuarioAdmin } from '@/lib/usuariosService'

const ADMIN_ROLES = new Set(['ADMIN_MUNICIPIO', 'ADMIN_INSTITUCION', 'ADMIN_SISTEMA'])
const roleLabel: Record<string, string> = { ADMIN_SISTEMA: 'Administrador sistema', ADMIN_INSTITUCION: 'Administrador institución', ADMIN_MUNICIPIO: 'Administrador organismo', UNIDAD_TECNICA: 'Unidad técnica', UNIDAD_COMPRA: 'Unidad de compra', JURIDICO: 'Jurídico', JEFE_COMPRAS: 'Jefatura de compras', LECTOR: 'Lector' }

export default function UsuariosAdminPage() {
  const { user, profile, loading: authLoading } = useAuth()
  const [users, setUsers] = useState<UsuarioAdmin[]>([])
  const [roles, setRoles] = useState<RolAdmin[]>([])
  const [institutions, setInstitutions] = useState<InstitucionAdmin[]>([])
  const [query, setQuery] = useState('')
  const [showInactive, setShowInactive] = useState(false)
  const [showForm, setShowForm] = useState(false)
  const [editing, setEditing] = useState<UsuarioAdmin | null>(null)
  const [form, setForm] = useState({ email: '', nombre: '', rolId: '', institucionId: '' })
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)
  const [temporaryPassword, setTemporaryPassword] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const isSystemAdmin = profile?.rol === 'ADMIN_SISTEMA'

  const load = async () => { try { const [meta, result] = await Promise.all([obtenerMetadatosUsuarios(), listarUsuarios()]); setRoles(meta.roles); setInstitutions(meta.instituciones); setUsers(result.usuarios); if (!form.institucionId && meta.instituciones[0]) setForm((current) => ({ ...current, institucionId: meta.instituciones[0].id })) } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'No se pudo cargar la gestión de usuarios.' }) } }
  useEffect(() => { if (user && ADMIN_ROLES.has(profile?.rol || '')) void load() }, [profile?.rol, user])

  const filtered = useMemo(() => users.filter((item) => (showInactive || item.activo) && `${item.nombre || ''} ${item.email} ${item.rol || ''}`.toLowerCase().includes(query.toLowerCase())), [query, showInactive, users])
  const openCreate = () => { setEditing(null); setForm({ email: '', nombre: '', rolId: roles[0]?.id?.toString() || '', institucionId: institutions[0]?.id || '' }); setShowForm(true); setMessage(null) }
  const openEdit = (item: UsuarioAdmin) => { setEditing(item); setForm({ email: item.email, nombre: item.nombre || '', rolId: item.rol_id?.toString() || '', institucionId: item.municipio_id || institutions[0]?.id || '' }); setShowForm(true); setMessage(null) }
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(null); setTemporaryPassword(null); try { if (editing) { await editarUsuario(editing.id, { nombre: form.nombre, rolId: Number(form.rolId) }); setMessage({ type: 'success', text: 'Usuario actualizado.' }) } else { const result = await crearUsuario({ email: form.email, nombre: form.nombre, rolId: Number(form.rolId), institucionId: form.institucionId }); setTemporaryPassword(result.contrasenaTemp); setMessage({ type: 'success', text: 'Usuario creado. Entrega la contraseña temporal por un canal seguro.' }) } setShowForm(false); await load() } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'No se pudo guardar el usuario.' }) } finally { setSaving(false) } }
  const toggle = async (item: UsuarioAdmin) => { setMessage(null); try { if (item.activo) await desactivarUsuario(item.id); else await activarUsuario(item.id); await load(); setMessage({ type: 'success', text: item.activo ? 'Usuario desactivado.' : 'Usuario activado.' }) } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'No se pudo cambiar el estado.' }) } }
  const reset = async (item: UsuarioAdmin) => { setMessage(null); try { const result = await resetearContrasena(item.id); setTemporaryPassword(result.contrasenaTemp); setMessage({ type: 'success', text: 'Contraseña temporal generada. Se muestra solo ahora.' }); await load() } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'No se pudo restablecer la contraseña.' }) } }

  if (authLoading) return <><Header /><main className="min-h-screen bg-gray-50 flex items-center justify-center text-gray-600">Cargando usuarios...</main></>
  if (!user || !ADMIN_ROLES.has(profile?.rol || '')) return <><Header /><main className="min-h-screen bg-gray-50 flex items-center justify-center p-6"><p className="text-gray-700">No tienes permisos para gestionar usuarios.</p></main></>
  return <><Header /><main className="min-h-screen bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4 mb-6"><div><p className="text-sm font-semibold text-teal-700">ADMINISTRACIÓN</p><h1 className="text-3xl font-bold text-gray-900 mt-1">Usuarios y permisos</h1><p className="text-gray-600 mt-2">Cada usuario recibe solo el acceso necesario para su función.</p></div><Button onClick={openCreate}><Plus className="w-4 h-4" /> Nuevo usuario</Button></div>
    {message && <Alert type={message.type} className="mb-4">{message.text}</Alert>}
    {temporaryPassword && <div className="mb-4 rounded-lg border border-amber-300 bg-amber-50 p-4 text-amber-900"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">Contraseña temporal</p><p className="text-sm mt-1">Cópiala y entrégala por un canal seguro. No volverá a mostrarse.</p><code className="inline-block mt-3 rounded bg-white px-3 py-2 font-mono text-lg tracking-wider">{temporaryPassword}</code></div><button type="button" title="Ocultar contraseña temporal" onClick={() => setTemporaryPassword(null)} className="p-1 hover:bg-amber-100 rounded"><X className="w-4 h-4" /></button></div></div>}
    {showForm && <section className="mb-6 bg-white border border-gray-200 rounded-lg p-6"><div className="flex items-center justify-between mb-4"><h2 className="font-bold text-gray-900">{editing ? 'Editar usuario' : 'Crear usuario'}</h2><button title="Cerrar formulario" onClick={() => setShowForm(false)} className="p-1 text-gray-500 hover:bg-gray-100 rounded"><X className="w-5 h-5" /></button></div><form onSubmit={submit} className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="text-sm font-semibold text-gray-700">Nombre completo<input required minLength={2} value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label>{!editing && <label className="text-sm font-semibold text-gray-700">Correo institucional<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label>}<label className="text-sm font-semibold text-gray-700">Rol<select required value={form.rolId} onChange={(e) => setForm({ ...form, rolId: e.target.value })} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal"><option value="">Selecciona un rol</option>{roles.map((role) => <option key={role.id} value={role.id}>{roleLabel[role.codigo] || role.nombre}</option>)}</select></label>{isSystemAdmin && !editing && <label className="text-sm font-semibold text-gray-700">Institución / organismo<select required value={form.institucionId} onChange={(e) => setForm({ ...form, institucionId: e.target.value })} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal"><option value="">Selecciona una institución</option>{institutions.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label>}<div className="md:col-span-2 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setShowForm(false)}>Cancelar</Button><Button type="submit" isLoading={saving}>{editing ? 'Guardar cambios' : 'Crear usuario'}</Button></div></form></section>}
    <section className="bg-white border border-gray-200 rounded-lg overflow-hidden"><div className="p-4 border-b border-gray-200 flex flex-col md:flex-row gap-3 md:items-center md:justify-between"><div className="relative flex-1 max-w-md"><Search className="absolute left-3 top-2.5 w-4 h-4 text-gray-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nombre, email o rol" className="w-full rounded-lg border border-gray-300 pl-9 pr-3 py-2 text-sm" /></div><label className="inline-flex items-center gap-2 text-sm text-gray-600"><input type="checkbox" checked={showInactive} onChange={(e) => setShowInactive(e.target.checked)} /> Mostrar inactivos</label></div><div className="divide-y divide-gray-100">{filtered.length === 0 ? <p className="p-6 text-gray-500">No hay usuarios que coincidan con el filtro.</p> : filtered.map((item) => <div key={item.id} className="p-4 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div className="flex items-center gap-3"><span className={`w-9 h-9 rounded-full flex items-center justify-center ${item.activo ? 'bg-teal-100 text-teal-800' : 'bg-gray-100 text-gray-500'}`}><UserCheck className="w-4 h-4" /></span><div><p className="font-semibold text-gray-900">{item.nombre || 'Sin nombre'}</p><p className="text-sm text-gray-600">{item.email} · {roleLabel[item.rol || ''] || item.rol || 'Sin rol'}</p><p className="text-xs text-gray-500 mt-1">{item.activo ? 'Activo' : 'Inactivo'}{item.ultimo_login ? ` · Último acceso ${new Date(item.ultimo_login).toLocaleDateString('es-CL')}` : ' · Sin acceso registrado'}</p></div></div><div className="flex flex-wrap gap-2"><button title="Editar usuario" onClick={() => openEdit(item)} className="inline-flex items-center gap-1 rounded-lg border border-gray-300 px-3 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50"><Edit3 className="w-3.5 h-3.5" /> Editar</button><button title="Restablecer contraseña" onClick={() => void reset(item)} className="inline-flex items-center gap-1 rounded-lg border border-amber-300 px-3 py-2 text-xs font-semibold text-amber-800 hover:bg-amber-50"><KeyRound className="w-3.5 h-3.5" /> Restablecer</button><button title={item.activo ? 'Desactivar usuario' : 'Activar usuario'} onClick={() => void toggle(item)} className={`inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold ${item.activo ? 'border-red-200 text-red-700 hover:bg-red-50' : 'border-teal-200 text-teal-700 hover:bg-teal-50'}`}>{item.activo ? <UserX className="w-3.5 h-3.5" /> : <UserCheck className="w-3.5 h-3.5" />}{item.activo ? 'Desactivar' : 'Activar'}</button></div></div>)}</div></section>
  </div></main></>
}
